export const palette = {
  slate: '#4C5C66',
  slateDeep: '#38454D',
  slateLight: '#8CA0AC',
  sage: '#5C8A63',
  sageDeep: '#446B4A',
  sageBright: '#84AE8A',
  brick: '#C24C42',
  brickDeep: '#9C3B33',
  brickBright: '#D97A6E',
  amber: '#C08A34',
  amberBright: '#D9A855',
  white: '#FFFFFF',
  black: '#000000',
};

export const lightTheme = {
  mode: 'light' as const,
  bg: '#F3F4F5',
  bgElevated: '#FFFFFF',
  card: '#FFFFFF',
  border: '#E1E4E6',
  text: '#1B1F22',
  textMuted: '#6B7378',
  primary: palette.slate,
  primaryGradient: [palette.slate, palette.slate] as const,
  primarySoft: '#E4E8EA',
  primaryText: '#FFFFFF',
  success: palette.sage,
  successGradient: [palette.sage, palette.sage] as const,
  successSoft: '#E4EDE5',
  danger: palette.brick,
  dangerGradient: [palette.brick, palette.brick] as const,
  dangerSoft: '#F5E4E1',
  warning: palette.amber,
  warningSoft: '#F3EBDB',
  accent: '#4C7A9B',
  accentSoft: '#E1EAF0',
  tabBar: '#FFFFFF',
  overlay: 'rgba(20,22,24,0.5)',
  inputBg: '#EEF0F1',
  shadow: 'rgba(76,92,102,0.16)',
};

export const darkTheme = {
  mode: 'dark' as const,
  bg: '#121416',
  bgElevated: '#1B1E21',
  card: '#1B1E21',
  border: '#2B2F33',
  text: '#F2F3F4',
  textMuted: '#93999D',
  primary: palette.slateLight,
  primaryGradient: [palette.slateLight, palette.slateLight] as const,
  primarySoft: '#26313A',
  primaryText: '#12181B',
  success: palette.sageBright,
  successGradient: [palette.sageBright, palette.sageBright] as const,
  successSoft: '#1F2A20',
  danger: palette.brickBright,
  dangerGradient: [palette.brickBright, palette.brickBright] as const,
  dangerSoft: '#332320',
  warning: palette.amberBright,
  warningSoft: '#332911',
  accent: '#7FAAC4',
  accentSoft: '#1D2C34',
  tabBar: '#17191B',
  overlay: 'rgba(0,0,0,0.72)',
  inputBg: '#22262A',
  shadow: 'rgba(140,160,172,0.2)',
};

export type Theme = Omit<typeof lightTheme, 'mode'> & { mode: 'light' | 'dark' };
